"""Makefile generation: assemble fragments into a package's Makefile.

The generated Makefile = the package's ``config/Makefile`` template with its
``<COMPILER_CONFIGURATION>`` placeholder replaced by, in order:

    compiler.mk   (central, shipped by configme)
    machine.mk    (central, shipped by configme)
    netCDF block  (auto-detected, unless the machine fragment overrides it)
    common.mk     (repo-owned dependency wiring)

See docs/DESIGN.md sec. 2 and sec. 5. The three-tier fragment lookup
(orchestrator/user/shipped) and the .configme manifest come in later slices;
this module currently resolves fragments from the shipped registry and reads
the template + common.mk from the repo (.configme/ first, then config/).
"""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path
from typing import Optional

from configme import data, netcdf

PLACEHOLDER = "<COMPILER_CONFIGURATION>"

# A machine fragment "provides netCDF" (and thus overrides auto-detection) if it
# assigns any of these variables.
_NETCDF_ASSIGN = re.compile(r"^\s*(INC_NC|LIB_NC|NC_FROOT|NC_CROOT)\s*=", re.M)


class GenerateError(Exception):
    """A Makefile could not be generated (missing fragment, template, etc.)."""


def _find_repo_file(cfgroot: Path, relname: str) -> Optional[Path]:
    """Locate a repo config file, preferring .configme/ over config/."""
    for base in (cfgroot / ".configme", cfgroot / "config"):
        p = base / relname
        if p.is_file():
            return p
    return None


def _shipped_fragment(kind: str, name: str) -> Path:
    """Resolve a shipped compiler/machine fragment, or raise listing options."""
    if kind == "machine":
        path = data.MACHINES_DIR / f"{name}.mk"
        available = data.machines()
    else:
        path = data.COMPILERS_DIR / f"{name}.mk"
        available = data.compilers()
    if not path.is_file():
        raise GenerateError(
            f"{kind} fragment '{name}' not found. "
            f"Available {kind}s: {', '.join(available) or '(none)'}"
        )
    return path


def _atomic_write(path: Path, text: str) -> None:
    """Write text to path atomically (temp file in the same dir + rename), so an
    interrupted run never leaves a corrupt or half-written Makefile."""
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".configme-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _netcdf_block() -> str:
    info = netcdf.detect()
    return (
        f"# netCDF — auto-detected by configme (source: {info.source}).\n"
        f"NC_FROOT = {info.nc_froot or ''}\n"
        f"NC_CROOT = {info.nc_croot or ''}\n"
        f"INC_NC = {info.inc_nc}\n"
        f"LIB_NC = {info.lib_nc}"
    )


def generate_makefile(root: Path, machine: str, compiler: str,
                      config_subdir: str = "") -> Path:
    """Generate <root>/<config_subdir>/Makefile and return its path.

    Raises GenerateError on any missing input, NetcdfError if netCDF cannot be
    resolved and the machine fragment does not override it.
    """
    root = Path(root)
    cfgroot = root / config_subdir if config_subdir else root
    if not cfgroot.is_dir():
        raise GenerateError(f"directory not found: {cfgroot}")

    template_path = _find_repo_file(cfgroot, "Makefile")
    if template_path is None:
        raise GenerateError(
            f"no Makefile template found in {cfgroot}/.configme/ or {cfgroot}/config/"
        )
    template = template_path.read_text()
    if PLACEHOLDER not in template:
        raise GenerateError(
            f"template {template_path} has no {PLACEHOLDER} placeholder"
        )

    compiler_mk = _shipped_fragment("compiler", compiler).read_text()
    machine_mk = _shipped_fragment("machine", machine).read_text()
    common_path = _find_repo_file(cfgroot, "common.mk")

    header = (
        f"## Generated by configme — machine={machine}, compiler={compiler}.\n"
        f"## Do not edit this block by hand; rerun `configme` to regenerate."
    )
    parts = [header, compiler_mk, machine_mk]

    # netCDF: auto-detect and inject, unless the machine fragment overrides it.
    if not _NETCDF_ASSIGN.search(machine_mk):
        parts.append(_netcdf_block())

    if common_path is not None:
        parts.append(common_path.read_text())

    compile_info = "\n\n".join(p.strip("\n") for p in parts)
    makefile = template.replace(PLACEHOLDER, compile_info)

    out_path = cfgroot / "Makefile"
    _atomic_write(out_path, makefile)
    return out_path
