"""`configme status`: read-only inspection of an installed stack.

Where ``install`` reports what a run just *did*, ``status`` answers what is true
on disk *now* — independent of any run. It reconstructs the expected world the
same way ``install`` does (the checkout's manifest names the primary ->
``build_plan`` -> ``root_for``) and probes the disk, reporting per-component
state across five stages:

  present  each cloned component (incl. data_packages / subpackages) is on disk
  link     each inter-component build symlink resolves
  config   each makefile-template package has a configme-generated Makefile
  build    each declared ``[package.artifacts]`` file exists (per variant)
  extra    each orchestrator extra (data_link / runme_config) is present

The report is **package-centric**: one row per component, laid out as a
containment tree (orchestrator -> components -> subpackages) with the stages as
columns, so a single glance shows each package's branch and how far along it is
(present / linked / configured / built). Orchestrator extras, which belong to no
single package, are summarised on their own line.

Generality comes from driving every check off the same registry metadata that
drives ``install`` — not a separate hand-maintained checklist — so a new
package/orchestrator/extra is covered automatically.

The inspection is **pure**: no clones, no Makefile regeneration, no config
writes, no prompts. The same table (filtered to outstanding rows) is appended as
a compact "current status" block to the ``install`` and ``config`` summaries
(see ``pending_block``).
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from configme import color, data, install

# "ok" is the only good state; everything else is reported.
#   missing  a required component/link that should be present is not
#   broken   a symlink that dangles (its target does not exist)
#   partial  some but not all artifacts of a build variant exist (half-built)
#   pending  a soft/deferred absence: an optional or data repo not cloned, a
#            build not started, an extra not yet set up — intended, not an error
_OK = "ok"
# States that signal a genuine problem (non-zero exit). ``pending`` is excluded:
# it is an intended/deferred gap, not a failure.
_HARD = {"missing", "broken", "partial"}

# Marker written into every configme-generated Makefile (see generate.py). Its
# presence distinguishes a generated Makefile from a package's committed
# ``config/Makefile`` template, so ``config`` state reflects a real configure run.
_GENERATED_MARK = "Generated by configme"

# The four per-package stages, in report order, paired with their column titles.
# ``extra`` is deliberately not here — extras are orchestrator-level, rendered on
# their own line, not as a package row.
_STAGES = [
    ("repo", "present"),
    ("link", "links"),
    ("config", "config"),
    ("build", "build"),
]

# Severity ranking: aggregating several checks of one stage into a single cell
# keeps the worst state. ``ok`` is lowest so a stage is green only when *every*
# underlying check is ok.
_SEV = {"ok": 0, "pending": 1, "partial": 2, "broken": 3, "missing": 4}

# One-glyph cell renderings. ``missing`` and ``broken`` share the loud ✗ (their
# detail column disambiguates); a stage that does not apply to a package renders
# as the calm em-dash from ``_NA``.
_GLYPH = {
    "ok": "✓",
    "missing": "✗",
    "broken": "✗",
    "partial": "~",
    "pending": "o",
}
_NA = "—"

# ANSI attributes per state: ``ok`` green, the hard problems red (``missing`` also
# bold — it's the loudest), the half-state yellow, deferred ``pending`` cyan.
_STATE_STYLE = {
    "ok": ("green",),
    "missing": ("red", "bold"),
    "broken": ("red",),
    "partial": ("yellow",),
    "pending": ("cyan",),
}

# Verbose-only word labels (the old flat-list rendering, reused for the per-check
# detail lines under a row when ``--verbose`` is set).
_MARK = {
    "ok": "ok     ",
    "missing": "MISSING",
    "broken": "broken ",
    "partial": "partial",
    "pending": "pending",
}


@dataclass
class Check:
    """One inspected fact about the stack on disk."""
    category: str   # "repo" | "link" | "config" | "build" | "extra"
    pkg: str        # owning package (row it belongs to); "" for orchestrator extras
    name: str       # component / link / artifact label (for verbose detail)
    state: str      # see the state vocabulary above
    detail: str = ""    # short human note (e.g. "optional; not cloned")
    hint: str = ""      # a command that resolves a non-ok state
    variant: str = ""   # build variant (serial/omp) for a build check, else ""


# --------------------------------------------------------------- probing

def _is_checkout(dest: Path) -> bool:
    """True if ``dest`` holds a git checkout. ``.git`` is a directory for a
    normal clone and a file for a submodule/worktree, so probe its existence
    rather than its type."""
    return (dest / ".git").exists()


def inspect(plan, root: Path) -> List[Check]:
    """Probe the disk for the state of every component in ``plan`` rooted at
    ``root``. Read-only. Returns checks tagged with their owning package and
    stage; the renderer groups them into the per-package table."""
    pkgs = data.packages()
    checks: List[Check] = []
    checks += _inspect_repos(plan, root)
    checks += _inspect_links(plan, root, pkgs)
    checks += _inspect_config(plan, root, pkgs)
    checks += _inspect_builds(plan, root, pkgs)
    checks += _inspect_extras(plan, root)
    return checks


def _owner_of(node) -> str:
    """The package whose ``configme install`` covers ``node``: the node itself if
    it clones, else its parent (a subpackage is configured/built by its parent's
    install)."""
    return node.name if node.clone else (node.parent or node.name)


def _inspect_repos(plan, root: Path) -> List[Check]:
    """Each component is present on disk. A cloned component is a real git
    checkout; a subpackage rides its parent's checkout, so it is "present" when
    its dest directory exists (no ``.git`` of its own)."""
    out: List[Check] = []
    for node in plan.nodes:
        dest = install.dest_of(node, plan, root)
        if not node.clone:
            # Subpackage: present iff its dir exists inside the parent checkout.
            state = _OK if dest.exists() else "missing"
            out.append(Check("repo", node.name, node.name, state,
                             hint=f"configme install {_owner_of(node)}"))
            continue
        if _is_checkout(dest):
            out.append(Check("repo", node.name, node.name, _OK))
        elif node.clone_policy in ("optional", "prompt"):
            detail = ("optional; not cloned" if node.clone_policy == "optional"
                      else "not cloned (opt-in)")
            out.append(Check("repo", node.name, node.name, "pending",
                             detail=detail,
                             hint=f"configme install {node.name}"))
        else:
            out.append(Check("repo", node.name, node.name, "missing",
                             hint=f"configme install {node.name}"))
    return out


def _inspect_links(plan, root: Path, pkgs) -> List[Check]:
    """Each non-primary package's build symlinks resolve. Mirrors the resolution
    in ``install``'s link phase, but only reads: a present symlink whose target
    exists is ``ok``; a dangling one is ``broken``; an absent one is ``missing``
    when its dependency is on disk (re-link), else ``pending`` (install the dep
    first)."""
    out: List[Check] = []
    relink = f"configme install {plan.primary.name}"
    present_dirs = {n.name: install.dest_of(n, plan, root) for n in plan.nodes}
    for node in plan.nodes:
        if node.name == plan.primary.name:
            continue
        node_root = install.dest_of(node, plan, root)
        if not node_root.exists():
            continue  # package not present; its links are not relevant yet
        for link in node.links:
            dep_dest = present_dirs.get(link.dep)
            if dep_dest is None and link.dep in pkgs:
                sub = (plan.orchestrator.component_paths.get(
                       link.dep, pkgs[link.dep].dir)
                       if plan.orchestrator else pkgs[link.dep].dir)
                dep_dest = root / sub
            link_path = node_root / link.path
            dep_present = dep_dest is not None and dep_dest.exists()
            label = f"{node.name}/{link.path} -> {link.dep}"
            if link_path.is_symlink():
                if link_path.resolve().exists():
                    out.append(Check("link", node.name, label, _OK))
                else:
                    out.append(Check("link", node.name, label, "broken",
                                     detail="symlink target missing",
                                     hint=(relink if dep_present
                                           else f"configme install {link.dep}")))
            elif link_path.exists():
                out.append(Check("link", node.name, label, _OK))  # real dir/file
            elif dep_present:
                out.append(Check("link", node.name, label, "missing",
                                 detail="dependency present but not linked",
                                 hint=relink))
            else:
                out.append(Check("link", node.name, label, "pending",
                                 detail=f"dependency '{link.dep}' not present",
                                 hint=f"configme install {link.dep}"))
    return out


def _inspect_config(plan, root: Path, pkgs) -> List[Check]:
    """Each makefile-template package carries a configme-generated Makefile. A
    package with ``config_style != "makefile-template"`` needs no configure step
    and is not reported (its ``config`` cell renders n/a). The generated Makefile
    lives at ``<dest>/<config_subdir>/Makefile`` and is distinguished from the
    committed template by the ``Generated by configme`` header (see generate.py):
    a package's own ``config/Makefile`` template is *not* counted as configured."""
    out: List[Check] = []
    for node in plan.nodes:
        pkg = pkgs.get(node.name)
        if pkg is None or pkg.config_style != "makefile-template":
            continue
        dest = install.dest_of(node, plan, root)
        if not dest.exists():
            continue  # a missing checkout is already reported by _inspect_repos
        cfgroot = dest / pkg.config_subdir if pkg.config_subdir else dest
        makefile = cfgroot / "Makefile"
        hint = f"configme install {_owner_of(node)}"
        if _has_generated_makefile(makefile):
            out.append(Check("config", node.name, node.name, _OK))
        else:
            out.append(Check("config", node.name, node.name, "pending",
                             detail="Makefile not generated", hint=hint))
    return out


def _has_generated_makefile(path: Path) -> bool:
    """True if ``path`` is a Makefile that configme generated (carries the marker
    header). A read error or a bare template both count as not-configured."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            return _GENERATED_MARK in fh.read(4096)
    except OSError:
        return False


def _inspect_builds(plan, root: Path, pkgs) -> List[Check]:
    """Each declared build artifact exists, per variant. A package with no
    ``[package.artifacts]`` is not reported. A variant with all artifacts present
    is ``ok``; none present is ``pending`` (not built yet — possibly deferred on
    purpose); some present is ``partial`` (a genuinely incomplete build)."""
    out: List[Check] = []
    for node in plan.nodes:
        pkg = pkgs.get(node.name)
        if pkg is None or not pkg.artifacts:
            continue
        dest = install.dest_of(node, plan, root)
        if not dest.exists():
            continue  # a missing checkout is already reported as a repo problem
        hint = f"configme install {_owner_of(node)} --build-deps"
        for variant, paths in pkg.artifacts.items():
            present = [p for p in paths if (dest / p).exists()]
            label = f"{node.name} ({variant})"
            if len(present) == len(paths):
                out.append(Check("build", node.name, label, _OK, variant=variant))
            elif not present:
                out.append(Check("build", node.name, label, "pending",
                                 detail="not built", hint=hint, variant=variant))
            else:
                missing = [p for p in paths if p not in present]
                out.append(Check("build", node.name, label, "partial",
                                 detail=f"missing {', '.join(missing)}",
                                 hint=hint, variant=variant))
    return out


def _inspect_extras(plan, root: Path) -> List[Check]:
    """Each orchestrator extra is present on disk. ``data_link``/``runme_config``
    are probed; ``pip_package`` is skipped because an installed pip package
    cannot be reliably probed from the checkout. (Auxiliary/data repos are not
    extras — they are packages, probed by ``_inspect_repos``.)"""
    out: List[Check] = []
    orch = plan.orchestrator
    if orch is None or not orch.extras:
        return out
    install_hint = f"configme install {orch.name}"
    for name, value in orch.extras.items():
        if name == "data_link":
            for label in (value if isinstance(value, list) else [value]):
                link_path = root / label
                if link_path.is_symlink() or link_path.exists():
                    out.append(Check("extra", "", f"data_link {label}", _OK))
                else:
                    # A data link points at a site-specific path configme can't
                    # know, so the resolving hint is the bare symlink command to
                    # run by hand, not a `configme install` re-run.
                    out.append(Check("extra", "", f"data_link {label}", "pending",
                                     detail="not linked",
                                     hint=f"ln -s /path/to/{label} {link_path}"))
        elif name == "runme_config":
            if value:
                if (root / ".runme" / "config.toml").exists():
                    out.append(Check("extra", "", "runme_config", _OK))
                else:
                    out.append(Check("extra", "", "runme_config", "pending",
                                     detail=".runme/config.toml not created",
                                     hint=install_hint))
    return out


# --------------------------------------------------------------- reporting

def has_problems(checks: List[Check]) -> bool:
    """True if any check is in a hard-problem state (missing/broken/partial).
    ``pending`` items are deliberately not problems."""
    return any(c.state in _HARD for c in checks)


@dataclass
class _Row:
    """One package's line in the table: its place in the containment tree, its
    on-disk branch, and the aggregated state of each stage."""
    name: str
    depth: int
    branch: str
    # stage category -> (state | None, detail); None means the stage is n/a.
    cells: Dict[str, Tuple[Optional[str], str]] = field(default_factory=dict)


def _display_order(plan) -> List[Tuple[object, int]]:
    """Nodes as a containment tree: the primary at depth 0, its components at
    depth 1, each subpackage one level below its parent. Returns ``(node, depth)``
    in render order (parent immediately followed by its subtree)."""
    primary = plan.primary
    by_name = {n.name: n for n in plan.nodes}
    children: Dict[str, List[object]] = defaultdict(list)
    tops: List[object] = []
    for n in plan.nodes:
        if n.name == primary.name:
            continue
        if n.parent and n.parent in by_name:
            children[n.parent].append(n)
        else:
            tops.append(n)

    order: List[Tuple[object, int]] = []

    def emit(node, depth):
        order.append((node, depth))
        for child in children.get(node.name, ()):
            emit(child, depth + 1)

    emit(primary, 0)
    for node in tops:
        emit(node, 1)
    return order


def _branch_of(node, plan, root: Path) -> str:
    """The checkout's current branch (the truth on disk). Falls back to the
    node's pinned ref, then ``-`` when nothing is known / present."""
    dest = install.dest_of(node, plan, root)
    if dest.exists():
        branch = install._git_branch(dest)
        if branch:
            return branch
    return node.ref or "-"


def _aggregate(checks: List[Check]) -> Tuple[Optional[str], str]:
    """Collapse a package's checks for one stage into a single cell: the worst
    state and its detail. No checks -> ``(None, "")`` (stage n/a for this pkg)."""
    if not checks:
        return None, ""
    worst = max(checks, key=lambda c: _SEV.get(c.state, 0))
    return worst.state, worst.detail


def _aggregate_build(checks: List[Check]) -> Tuple[Optional[str], str]:
    """Like ``_aggregate`` but the detail names the affected variants, so the
    build cell can show *which* parts are outstanding (e.g. ``serial, omp``)."""
    if not checks:
        return None, ""
    bad = [c for c in checks if c.state != _OK]
    if not bad:
        return _OK, ""
    worst = max(bad, key=lambda c: _SEV.get(c.state, 0))
    variants = ", ".join(c.variant for c in bad if c.variant)
    return worst.state, variants


def _rows(plan, checks: List[Check], root: Path) -> List[_Row]:
    """Build one ``_Row`` per package, in containment-tree order."""
    by_pkg: Dict[str, Dict[str, List[Check]]] = defaultdict(lambda: defaultdict(list))
    for c in checks:
        if c.pkg:
            by_pkg[c.pkg][c.category].append(c)
    rows: List[_Row] = []
    for node, depth in _display_order(plan):
        stage = by_pkg.get(node.name, {})
        cells = {
            "repo": _aggregate(stage.get("repo", [])),
            "link": _aggregate(stage.get("link", [])),
            "config": _aggregate(stage.get("config", [])),
            "build": _aggregate_build(stage.get("build", [])),
        }
        rows.append(_Row(node.name, depth, _branch_of(node, plan, root), cells))
    return rows


def _tree_label(row: _Row) -> str:
    """The package column text: two spaces of indent per depth, a ``↳`` connector
    on every nested row so the containment pattern reads the same at every level."""
    if row.depth == 0:
        return row.name
    return "  " * row.depth + "↳ " + row.name


def _glyph_cell(state: Optional[str]) -> str:
    """A single-glyph stage cell (colored). ``None`` -> the dim n/a em-dash."""
    if state is None:
        return color.style(_NA, "dim")
    return color.style(_GLYPH.get(state, "?"), *_STATE_STYLE.get(state, ()))


def _build_cell(state: Optional[str], detail: str) -> str:
    """The build column: a glyph, plus the affected variants when outstanding."""
    if state is None:
        return color.style(_NA, "dim")
    glyph = color.style(_GLYPH.get(state, "?"), *_STATE_STYLE.get(state, ()))
    return f"{glyph} {detail}" if detail else glyph


def _pad(text: str, width: int, visible: int) -> str:
    """Left-justify ``text`` to ``width`` columns given its ``visible`` length
    (``text`` may carry zero-width ANSI codes, so ``ljust`` can't be trusted)."""
    return text + " " * max(0, width - visible)


def _render_table(rows: List[_Row]) -> List[str]:
    """The header row plus one line per package. Single-glyph stage columns are
    padded by visible width (glyphs are one column wide); the build column is
    last so its variable-width detail can run ragged."""
    labels = [_tree_label(r) for r in rows]
    pkg_w = max([len("package")] + [len(x) for x in labels]) + 2
    br_w = max([len("branch")] + [len(r.branch) for r in rows]) + 2
    # Column titles for the single-glyph stages; width = title + 2-space gutter.
    glyph_titles = [t for cat, t in _STAGES if cat != "build"]
    col_w = {t: len(t) + 2 for t in glyph_titles}

    header = "  " + "package".ljust(pkg_w) + "branch".ljust(br_w)
    header += "".join(t.ljust(col_w[t]) for t in glyph_titles) + "build"
    lines = [header]

    for row, label in zip(rows, labels):
        line = "  " + label.ljust(pkg_w) + row.branch.ljust(br_w)
        for cat, title in _STAGES:
            state, detail = row.cells[cat]
            if cat == "build":
                line += _build_cell(state, detail)
            else:
                line += _pad(_glyph_cell(state), col_w[title], 1)
        lines.append(line.rstrip())
    return lines


def _extras_line(checks: List[Check]) -> Optional[str]:
    """A one-line summary of orchestrator extras (they belong to no package)."""
    extras = [c for c in checks if c.category == "extra"]
    if not extras:
        return None
    parts = [f"{c.name} {_glyph_cell(c.state)}" for c in extras]
    return "  extras: " + "   ".join(parts)


def _install_closure(name: str) -> set:
    """Package names that ``configme install <name>`` would touch (itself + its
    resolved dependencies + subpackages) — i.e. everything a ``--build-deps`` run
    of ``name`` also configures and builds. Falls back to ``{name}`` if the plan
    can't be built."""
    try:
        return {n.name for n in install.build_plan(name).nodes}
    except Exception:
        return {name}


def _parse_install(cmd: str) -> Tuple[Optional[str], bool]:
    """Parse a ``configme install <target> [--build-deps]`` command into
    ``(target, builds)``. Returns ``(None, False)`` for anything else (e.g. a
    raw ``ln -s`` data-link hint), which is never reduced away."""
    parts = cmd.split()
    if len(parts) >= 3 and parts[:2] == ["configme", "install"]:
        return parts[2], parts[-1] == "--build-deps"
    return None, False


def _command_groups(checks: List[Check],
                    extra: Tuple[str, ...] = ()) -> List[Tuple[str, List[str]]]:
    """Group the outstanding commands into ``(primary, [specific, ...])`` pairs.

    Commands collapse along the dependency graph: a command ``A`` (target ``a``,
    builds?) is *dominated* by another listed command ``B`` (target ``b``) when

      * ``a`` is in ``b``'s install closure — installing ``b`` also touches ``a``;
      * ``B`` covers what ``A`` needs — if ``A`` builds, ``B`` must ``--build-deps``
        too (a plain install configures/links but does not build); and
      * ``B`` is genuinely broader — a different (ancestor) target, or the same
        target with ``--build-deps`` dominating a plain one.

    A dominated command is not dropped: it is nested under its broadest dominator
    as a more-specific alternative, so the footer reads "run this one umbrella
    command, *or* run these individual ones". Same-target weaker duplicates (a
    plain install shadowed by a ``--build-deps`` of the same target) carry no new
    information and are dropped outright. Non-install commands (e.g. a raw
    ``ln -s`` data-link hint) never reduce and always stand alone."""
    ordered: List[str] = []
    for c in checks:
        if c.state != _OK and c.hint and c.hint not in ordered:
            ordered.append(c.hint)
    for cmd in extra:
        if cmd and cmd not in ordered:
            ordered.append(cmd)

    closures = {}
    for cmd in ordered:
        target, _ = _parse_install(cmd)
        if target is not None and target not in closures:
            closures[target] = _install_closure(target)

    def dominators(cmd: str) -> List[str]:
        a, a_builds = _parse_install(cmd)
        if a is None:
            return []
        doms: List[str] = []
        for other in ordered:
            if other == cmd:
                continue
            b, b_builds = _parse_install(other)
            if b is None or a not in closures.get(b, {a}):
                continue
            if a_builds and not b_builds:
                continue  # B is a plain install; it wouldn't build A
            if b != a or (b_builds and not a_builds):
                doms.append(other)
        return doms

    dom = {cmd: dominators(cmd) for cmd in ordered}
    primaries = [cmd for cmd in ordered if not dom[cmd]]

    groups: List[Tuple[str, List[str]]] = []
    for primary in primaries:
        p_target, _ = _parse_install(primary)
        kids: List[str] = []
        for cmd in ordered:
            if not dom[cmd]:
                continue  # itself a primary
            c_target, _ = _parse_install(cmd)
            if c_target == p_target:
                continue  # same-target weaker duplicate — drop, don't nest
            # Attach to the first primary that dominates it, so each specific
            # command is listed under exactly one umbrella.
            chosen = next((d for d in dom[cmd] if not dom[d]), None)
            if chosen == primary:
                kids.append(cmd)
        groups.append((primary, kids))
    return groups


def _resolve_commands(checks: List[Check], extra: Tuple[str, ...] = ()) -> List[str]:
    """The minimal list of umbrella commands (one per group) — the flat form used
    when only the primaries are needed. See ``_command_groups`` for the reduction."""
    return [primary for primary, _ in _command_groups(checks, extra)]


def _command_lines(groups: List[Tuple[str, List[str]]]) -> List[str]:
    """Render command groups: each umbrella on a ``→`` line, with any specific
    alternatives listed under an "or run individually" note."""
    lines: List[str] = []
    for primary, kids in groups:
        lines.append(f"  {color.style('→', 'cyan')} {color.hint(primary)}")
        if kids:
            lines.append(f"      {color.hint('or run individually:')}")
            lines += [f"        {color.hint(k)}" for k in kids]
    return lines


def _summary(rows: List[_Row], checks: List[Check]) -> str:
    """The one-line tally under the table."""
    n = len(rows)
    problems = sum(1 for c in checks if c.state in _HARD)
    pending = sum(1 for c in checks if c.state == "pending")
    head = f"{n} package{'s' if n != 1 else ''}"
    if not problems and not pending:
        return head + " · " + color.ok("all present and built")
    bits = []
    if problems:
        bits.append(color.err(f"{problems} problem{'s' if problems != 1 else ''}"))
    if pending:
        bits.append(color.warn(f"{pending} pending"))
    return head + " · " + ", ".join(bits)


def _detail_lines(row: _Row, checks: List[Check]) -> List[str]:
    """Verbose expansion: the underlying non-ok checks for a package, one per
    line, indented under its row."""
    out: List[str] = []
    for c in checks:
        if c.pkg == row.name and c.state != _OK:
            mark = color.style(_MARK.get(c.state, c.state), *_STATE_STYLE.get(c.state, ()))
            s = f"      [{mark}] {c.name}"
            if c.detail:
                s += f"  ({c.detail})"
            if c.hint:
                s += f"  -> {color.hint(c.hint)}"
            out.append(s)
    return out


def render(plan, checks: List[Check], root: Path, *, verbose: bool = False) -> str:
    """Full ``configme status`` report: a package-centric table (branch + the
    present/links/config/build stages), an extras line, a one-line summary and
    the minimal set of commands to clear anything outstanding. ``verbose`` adds
    the underlying per-check detail beneath each package. The returned string ends
    in a newline so the caller's ``print`` leaves a blank line before the prompt."""
    rows = _rows(plan, checks, root)
    lines = [color.header(f"configme status: {plan.primary.name} at {root}"), ""]

    table = _render_table(rows)
    lines.append(table[0])  # header
    for row, body in zip(rows, table[1:]):
        lines.append(body)
        if verbose:
            lines += _detail_lines(row, checks)

    extras = _extras_line(checks)
    if extras:
        lines.append(extras)

    lines += ["", _summary(rows, checks)]
    lines += _command_lines(_command_groups(checks))
    return "\n".join(lines) + "\n"


def _row_outstanding(row: _Row) -> bool:
    """True if any of a row's stages is present and not ok."""
    return any(state not in (None, _OK) for state, _ in row.cells.values())


def pending_block(plan, checks: List[Check], root: Path,
                  extra_commands: Tuple[str, ...] = ()) -> str:
    """A compact "current status" block for the ``install``/``config`` summary:
    the package table filtered to rows with anything outstanding, plus the
    minimal command list (``extra_commands`` — e.g. deferred follow-ups — are
    folded into that same reduced list). Returns an empty string when the disk is
    fully in order and there is nothing to append."""
    rows = [r for r in _rows(plan, checks, root) if _row_outstanding(r)]
    extras_notok = [c for c in checks if c.category == "extra" and c.state != _OK]
    groups = _command_groups(checks, extra_commands)
    if not rows and not extras_notok and not groups:
        return ""

    lines = ["", color.header("Current status (configme status):")]
    if rows:
        lines += _render_table(rows)
    extras = _extras_line(extras_notok)
    if extras:
        lines.append(extras)
    if groups:
        lines.append("")
        lines += _command_lines(groups)
    return "\n".join(lines)
